### ISSUE TITLE
Update needed for Netbox 4.0

### ISSUE THREAD

**Issue by DatPenguin** [ArnesSI/netbox-powerdns-sync#11]
Hi,

There are some breaking changes in Netbox 4.0, including the following:

`from extras.plugins import PluginConfig` should be replaced by `from netbox.plugins import PluginConfig`.

I'm not sure what else needs to be changed, but is an update planned to be compatible with Netbox 4.0 ? Thanks :)

P.S.: [Here are the changes from Netbox Doc](https://docs.netbox.dev/en/stable/plugins/development/migration-v4/).

**Comment by gtr34mspec** [comment]
Hey @K0HAX 

Netbox 4.2.4 could not migrate with the following error with the specified modification.
Please let me know if you know how to fix this.
-----
(venv) # python3.12 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib64/python3.12/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/netbox/venv/lib64/python3.12/site-packages/netbox_powerdns_sync/models.py", line 18, in <module>
    from .utils import get_ip_host, make_canonical, is_reverse
  File "/opt/netbox/venv/lib64/python3.12/site-packages/netbox_powerdns_sync/utils.py", line 6, in <module>
    from extras.choices import ObjectChangeActionChoices
ImportError: cannot import name 'ObjectChangeActionChoices' from 'extras.choices' (/opt/netbox/netbox/extras/choices.py). Did you mean: 'ChangeActionChoices'?
(venv) #
-----

Best regards.
