### ISSUE TITLE
error on DB migration

### ISSUE THREAD

**Issue by kollross** [ArnesSI/netbox-powerdns-sync#2]
I'm getting the following error on the DB migration step.

```
(venv) ------------------------------------------------------------
[root@netbox] # python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox-3.5.8/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/netbox_powerdns_sync/models.py", line 17, in <module>
    from .utils import get_ip_host, make_canonical, is_reverse
  File "/opt/netbox-3.5.8/venv/lib/python3.9/site-packages/netbox_powerdns_sync/utils.py", line 15, in <module>
    def get_ip_host(ip:IPAddress) -> Device|VirtualMachine|None:
TypeError: unsupported operand type(s) for |: 'ModelBase' and 'ModelBase'
```

Netbox 3.5.8.
Python 3.9.2

**Comment by matejv** [comment]
Whoops. It seems like we're using some type hinting syntax that is only supported from python 3.10. I'll take a look how much code needs to be fixed and decide whether to remove problematic syntax or mark the plugin as compatible with python=>3.10.

**Comment by kollross** [comment]
Thank

I'll look into bumping the version of python on my end, now that I know that's the issue.

**Comment by kollross** [comment]
Upgrading to 9.10 resolved the issue...thanks.
