### ISSUE TITLE
PTR record generation

### ISSUE THREAD

**Issue by kollross** [ArnesSI/netbox-powerdns-sync#3]
I'm trying to wrap my head around how PTR records are created in .arpa zones.

Running it with out any options, doesn't populate the .arpa zone in question, and all the options for "Matchers" and "Naming methods" produce the same error of "Cannot set naming methods for reverse zone".

In my case, if you select an IP (say 192.168.1.5) in IPAM -> IP Addresses, I have populated the "DNS Name" field.  I would expect the 1.168.192.in-addr.arpa zone (or 168.192.in-addr.apa if you want less specific) so be populated.  

However running the script simply produces zero records added. 

Thanks.

**Comment by matejv** [comment]
Handling of reverse zones is a bit incomplete at this point.

I think it only works if you have `post_save_enabled:True` in plugin settings and setup a forward zone that will match the DNS names you are setting. In that case, when you create an IP address it will try to create a forward and reverse record for that IP an it should work.

Just syncing a reverse zone currently doesn't work. I'll take a look how to fix that.

**Comment by kollross** [comment]
Thanks

I enabled that "`post_save_enabled: True`" option, and it does generate the PTR record as expected..   However a I noticed a couple of oddities. 

If I select an IP (say 172.27.0.15) in netbox, and give it a dns hostname of (test.example.com) under the "DNS Name" field, it will immediately create both the forward and reverse records in PDNS.    However, if I run a sync on the forward job nothing is changed on PDNS (as expected), but running a sync on the Reverse zone, for some reason deletes the PTR record from PDNS.

Removing the "DNS Name" from the IP, appears to have no effect, producing this error.

```
Aug 30 08:45:28 netbox python3[2486]: 08:45:28 default: run_update_ip(job=<Job: 99f5b535-1a04-45b1-baba-e8f22b27db64>) (99f5b535-1a04-45b1-baba-e8f22b27db64)
Aug 30 08:45:28 netbox python3[74584]: error No forward zone found for IP:172.27.0.15/21
Aug 30 08:45:28 netbox python3[74584]: 08:45:28 [Job 99f5b535-1a04-45b1-baba-e8f22b27db64]: exception raised while executing (run_update_ip)
Aug 30 08:45:28 netbox python3[74584]: Traceback (most recent call last):
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/rq/worker.py", line 1428, in perform_job
Aug 30 08:45:28 netbox python3[74584]:     rv = job.perform()
Aug 30 08:45:28 netbox python3[74584]:          ^^^^^^^^^^^^^
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1278, in perform
Aug 30 08:45:28 netbox python3[74584]:     self._result = self._execute()
Aug 30 08:45:28 netbox python3[74584]:                    ^^^^^^^^^^^^^^^
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/rq/job.py", line 1315, in _execute
Aug 30 08:45:28 netbox python3[74584]:     result = self.func(*self.args, **self.kwargs)
Aug 30 08:45:28 netbox python3[74584]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 181, in run_update_ip
Aug 30 08:45:28 netbox python3[74584]:     raise e
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 171, in run_update_ip
Aug 30 08:45:28 netbox python3[74584]:     task.create_forward()
Aug 30 08:45:28 netbox python3[74584]:   File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 186, in create_forward
Aug 30 08:45:28 netbox python3[74584]:     raise PowerdnsSyncNoZoneFound(f"No forward zone found for IP:{self.ip}")
Aug 30 08:45:28 netbox python3[74584]: netbox_powerdns_sync.exceptions.PowerdnsSyncNoZoneFound: No forward zone found for IP:172.27.0.15/21 
```

Normally I wouldn't think this would be an issue, as I could schedule a sync to to clean up any removed DNS Names, but like I mentioned, the sync script deleted the properly created PTR records as well.

**Comment by matejv** [comment]
Yeah, handling PTR records is indeed a bit broken at the moment. We had not used this functionality in production so it wasn't tested much. I'll take a look at making it work better. At least so running a sync of a reverse zone would work as one would expect.

**Comment by matejv** [comment]
This is taking longer than I expected, sorry. But I am still planning to improve this.

**Comment by Charlie-Root** [comment]
I have created a PTR zone `0.72.10.in-addr.arpa.` and ran the sync, but nothing happens (with or without `post_save_enabled` set). 

Output:
`

2 | Info | Found 0 matching addresses to check
-- | -- | --
3 | Info | Found record count: netbox:0 pdns:0
4 | Info | Record change count: to_delete:0 to_create:0

`

With the option enabled i also see
`error No forward zone found for IP:10.72.0.10/24
`

**Comment by i3D-RyanHamel** [comment]
@matejv Is there an update on this? I see that @Charlie-Root has attached a pull request to this with a number of PTR record improvements, would that for ya? Thanks!

**Comment by Charlie-Root** [comment]
@i3D-RyanHamel doesn't seem to be maintained anymore.

**Comment by matejv** [comment]
Apologizes for not getting to this sooner. 

Honestly I just don't have the time available to maintain this plugin further. Just maintaining existing functionality, let alone adding new features.

Since I released the first version of netbox-powerdns-sync the excellent [netbox-plugin-dns](https://github.com/peteeckel/netbox-plugin-dns)  added [IPAM coupling](https://github.com/peteeckel/netbox-plugin-dns/blob/main/docs/using_netbox_dns.md#ipam-coupling) which was the main missing feature that motivated me to develop netbox-powerdns-sync. For our needs using netbox-plugin-dns + a script to sync it's records with powerdns API is plenty. I suggest other to take a look at this route as well.

**Comment by kollross** [comment]
I also have been using the netbox-plugin-dns plugin, would it be possible to share the script you are using to push those changes to powerdns?

**Comment by matejv** [comment]
> I also have been using the netbox-plugin-dns plugin, would it be possible to share the script you are using to push those changes to powerdns?

Here you go: [pdns_sync.py](https://gist.github.com/matejv/c59230ee723c5853a175c4c66b71e092)

**Comment by kollross** [comment]
Thank you.

**Comment by kollross** [comment]
You should try and submit this into the netbox_dns_plugin, project itself.  They have the scripts with similar things like exporting to BIND etc.  I think a lot of people would find this useful.
