### ISSUE TITLE
Not working with netbox 3.6.x

### ISSUE THREAD

**Issue by sirance** [ArnesSI/netbox-powerdns-sync#4]
I've been using this plugin on netbox 3.5.8 and it's been working brilliantly. However I've now upgraded netbox to 3.6.2, and also tested on 3.6.3 and I'm seeing the following errors when attempting to sync:

```
An exception occurred: ValueError: Cannot use QuerySet for "DeviceRole": Use a QuerySet for "Device".

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 239, in run_full_sync
    netbox_records = task.load_netbox_records()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 299, in load_netbox_records
    ip_addresses = self.get_addresses()
                   ^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/netbox_powerdns_sync/jobs.py", line 291, in get_addresses
    results = IPAddress.objects.filter(query_zone)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1404, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1464, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1270, in check_related_objects
    raise ValueError(
ValueError: Cannot use QuerySet for "DeviceRole": Use a QuerySet for "Device".
```

I know 3.6.x isn't officially listed as supported, but hopefully it doesn't require massive changes.

**Comment by matejv** [comment]
Sorry, it took me awhile to get to this. There is now version 0.0.8 that should work with netbox 3.6.

**Comment by sirance** [comment]
Brilliant, it's working once again, thank you so much!
