### ISSUE TITLE
Cannot install on netbox 3.6

### ISSUE THREAD

**Issue by andyfsimon** [ArnesSI/netbox-powerdns-sync#7]
Hi, 
I installed the plugin as specified in the readme but when I run the migrate script I get this error:

`
(venv) [root@netbox-ams netbox]# python3 manage.py migrate
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib64/python3.9/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netbox_powerdns_sync/models.py", line 18, in <module>
    from .utils import get_ip_host, make_canonical, is_reverse
  File "/opt/netbox/venv/lib64/python3.9/site-packages/netbox_powerdns_sync/utils.py", line 15, in <module>
    def get_ip_host(ip:IPAddress) -> Device|VirtualMachine|None:
TypeError: unsupported operand type(s) for |: 'ModelBase' and 'ModelBase'
`

Am I doing something wrong or I'm missing some package?

**Comment by matejv** [comment]
Hi

You are running python 3.9, however this plugin includes some syntax that in only supported in python 3.10 and onward.

It seems I forgot to update this fact in [pyproject.toml](https://github.com/ArnesSI/netbox-powerdns-sync/blob/master/pyproject.toml#L14), sorry.

Anyhow, you'll need to update your python version.
