### ISSUE TITLE
Zone Missing

### ISSUE THREAD

**Issue by ktoczyski** [ArnesSI/netbox-powerdns-sync#9]
Hello,

When I try sync zone which is configured on my DNS server I received Error:

"An exception occurred: PowerdnsSyncServerZoneMissing: Zone lan.example.eu not found on server ans01 
Traceback (most recent call last):   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_powerdns_sync/jobs.py", line 232, in run_full_sync     pdns_records = task.load_pdns_records()   File "/opt/netbox/venv/lib/python3.10/site-packages/netbox_powerdns_sync/jobs.py", line 338, in load_pdns_records     raise PowerdnsSyncServerZoneMissing( netbox_powerdns_sync.exceptions.PowerdnsSyncServerZoneMissing: Zone lan.example.eu not found on server ans01"

I also tried create new zone via NetBox panel but I have the same issue. Where is the problem?

**Comment by ju6ge** [comment]
you probable have not configured the api path to your server correctly. 

You need the full path like so:
https://{pdns_server_hostname}/api/v1

**Comment by iopsthecloud** [comment]
Or you probably missed the dot at the end of your domain.
